import type { Locale } from '@/lib/i18n/config'
import type { Cluster } from './clusters'
import type { Route } from './routes'

// In-app mirror of supabase/seed.sql careers, used for the zero-backend demo
// (recommendations run client-side). CURATED DEMO DATA — `marketRelevance` is a
// curated demo signal, NOT live labor-market data. Subject tags use the same
// keys as onboarding favorite_subjects so overlap scoring works.

export interface Career {
  slug: string
  route: Route
  clusterBias: Cluster[]
  subjectTags: string[]
  goalTags: string[]
  skillTags: string[]
  marketRelevance: number // 0..100 curated demo relevance
  name: Record<Locale, string>
}

export const CAREERS: Career[] = [
  // technological
  {
    slug: 'software_developer',
    route: 'technological',
    clusterBias: ['digital_innovator'],
    subjectTags: ['informatics', 'mathematics'],
    goalTags: ['build_products', 'high_income'],
    skillTags: ['coding', 'problem_solving'],
    marketRelevance: 95,
    name: { en: 'Software Developer', ru: 'Разработчик ПО', kk: 'Бағдарламашы' },
  },
  {
    slug: 'data_analyst',
    route: 'technological',
    clusterBias: ['digital_innovator', 'researcher'],
    subjectTags: ['mathematics', 'informatics'],
    goalTags: ['high_income', 'solve_problems'],
    skillTags: ['analysis', 'statistics'],
    marketRelevance: 90,
    name: { en: 'Data Analyst', ru: 'Аналитик данных', kk: 'Дерек талдаушысы' },
  },
  {
    slug: 'ai_specialist',
    route: 'technological',
    clusterBias: ['digital_innovator', 'researcher'],
    subjectTags: ['mathematics', 'informatics'],
    goalTags: ['build_future', 'high_income'],
    skillTags: ['ml', 'coding'],
    marketRelevance: 96,
    name: { en: 'AI Specialist', ru: 'Специалист по ИИ', kk: 'ЖИ маманы' },
  },
  {
    slug: 'cybersecurity_specialist',
    route: 'technological',
    clusterBias: ['digital_innovator', 'strategist'],
    subjectTags: ['informatics'],
    goalTags: ['protect_systems', 'high_income'],
    skillTags: ['security', 'networks'],
    marketRelevance: 92,
    name: {
      en: 'Cybersecurity Specialist',
      ru: 'Специалист по кибербезопасности',
      kk: 'Киберқауіпсіздік маманы',
    },
  },
  {
    slug: 'robotics_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'creator'],
    subjectTags: ['physics', 'informatics'],
    goalTags: ['build_things'],
    skillTags: ['engineering', 'coding'],
    marketRelevance: 85,
    name: { en: 'Robotics Engineer', ru: 'Инженер-робототехник', kk: 'Робототехника инженері' },
  },
  // research
  {
    slug: 'psychologist',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['biology', 'social_science'],
    goalTags: ['help_people', 'understand_people'],
    skillTags: ['empathy', 'analysis'],
    marketRelevance: 80,
    name: { en: 'Psychologist', ru: 'Психолог', kk: 'Психолог' },
  },
  {
    slug: 'medical_doctor',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['diagnosis', 'care'],
    marketRelevance: 88,
    name: { en: 'Doctor', ru: 'Врач', kk: 'Дәрігер' },
  },
  {
    slug: 'biologist',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['discover', 'understand_world'],
    skillTags: ['research', 'lab'],
    marketRelevance: 75,
    name: { en: 'Biologist', ru: 'Биолог', kk: 'Биолог' },
  },
  {
    slug: 'economist_researcher',
    route: 'research',
    clusterBias: ['researcher', 'strategist'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['understand_world', 'high_income'],
    skillTags: ['analysis', 'modeling'],
    marketRelevance: 78,
    name: { en: 'Economist', ru: 'Экономист', kk: 'Экономист' },
  },
  {
    slug: 'education_researcher',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['history', 'social_science'],
    goalTags: ['improve_education', 'help_people'],
    skillTags: ['research', 'writing'],
    marketRelevance: 70,
    name: {
      en: 'Education Researcher',
      ru: 'Исследователь в образовании',
      kk: 'Білім беру зерттеушісі',
    },
  },
  // managerial
  {
    slug: 'project_manager',
    route: 'managerial',
    clusterBias: ['strategist'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['lead_teams', 'high_income'],
    skillTags: ['planning', 'communication'],
    marketRelevance: 85,
    name: { en: 'Project Manager', ru: 'Менеджер проектов', kk: 'Жоба менеджері' },
  },
  {
    slug: 'entrepreneur',
    route: 'managerial',
    clusterBias: ['strategist', 'digital_innovator'],
    subjectTags: ['business_economics', 'mathematics'],
    goalTags: ['build_business', 'independence'],
    skillTags: ['leadership', 'risk'],
    marketRelevance: 88,
    name: { en: 'Entrepreneur', ru: 'Предприниматель', kk: 'Кәсіпкер' },
  },
  {
    slug: 'business_analyst',
    route: 'managerial',
    clusterBias: ['strategist', 'researcher'],
    subjectTags: ['mathematics', 'informatics', 'business_economics'],
    goalTags: ['solve_problems', 'high_income'],
    skillTags: ['analysis', 'communication'],
    marketRelevance: 84,
    name: { en: 'Business Analyst', ru: 'Бизнес-аналитик', kk: 'Бизнес-талдаушы' },
  },
  {
    slug: 'public_administration_specialist',
    route: 'managerial',
    clusterBias: ['strategist', 'social_leader'],
    subjectTags: ['history', 'social_science'],
    goalTags: ['serve_society', 'stability'],
    skillTags: ['policy', 'organization'],
    marketRelevance: 72,
    name: {
      en: 'Public Administration Specialist',
      ru: 'Специалист по госуправлению',
      kk: 'Мемлекеттік басқару маманы',
    },
  },
  {
    slug: 'lawyer',
    route: 'managerial',
    clusterBias: ['strategist', 'social_leader'],
    subjectTags: ['history', 'social_science'],
    goalTags: ['justice', 'high_income'],
    skillTags: ['argument', 'writing'],
    marketRelevance: 80,
    name: { en: 'Lawyer', ru: 'Юрист', kk: 'Заңгер' },
  },
  // social_humanitarian
  {
    slug: 'teacher',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['history', 'languages'],
    goalTags: ['help_people', 'shape_future'],
    skillTags: ['communication', 'patience'],
    marketRelevance: 82,
    name: { en: 'Teacher', ru: 'Учитель', kk: 'Мұғалім' },
  },
  {
    slug: 'hr_specialist',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['languages', 'social_science'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['empathy', 'organization'],
    marketRelevance: 76,
    name: { en: 'HR Specialist', ru: 'HR-специалист', kk: 'HR маманы' },
  },
  {
    slug: 'social_worker',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['social_science', 'history'],
    goalTags: ['help_people', 'make_impact'],
    skillTags: ['empathy', 'support'],
    marketRelevance: 70,
    name: { en: 'Social Worker', ru: 'Социальный работник', kk: 'Әлеуметтік қызметкер' },
  },
  {
    slug: 'diplomat',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['languages', 'history', 'geography'],
    goalTags: ['represent_country', 'travel'],
    skillTags: ['negotiation', 'languages'],
    marketRelevance: 74,
    name: { en: 'Diplomat', ru: 'Дипломат', kk: 'Дипломат' },
  },
  {
    slug: 'community_project_manager',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['social_science', 'history'],
    goalTags: ['make_impact', 'lead_teams'],
    skillTags: ['organization', 'communication'],
    marketRelevance: 68,
    name: {
      en: 'Community Project Manager',
      ru: 'Менеджер общественных проектов',
      kk: 'Қоғамдық жоба менеджері',
    },
  },
  // creative
  {
    slug: 'ux_ui_designer',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design', 'informatics'],
    goalTags: ['build_products', 'express'],
    skillTags: ['design', 'empathy'],
    marketRelevance: 88,
    name: { en: 'UX/UI Designer', ru: 'UX/UI-дизайнер', kk: 'UX/UI дизайнер' },
  },
  {
    slug: 'architect',
    route: 'creative',
    clusterBias: ['creator', 'strategist'],
    subjectTags: ['art_design', 'mathematics', 'physics'],
    goalTags: ['build_things', 'express'],
    skillTags: ['design', 'drafting'],
    marketRelevance: 80,
    name: { en: 'Architect', ru: 'Архитектор', kk: 'Сәулетші' },
  },
  {
    slug: 'journalist',
    route: 'creative',
    clusterBias: ['creator', 'social_leader'],
    subjectTags: ['languages', 'literature'],
    goalTags: ['tell_stories', 'make_impact'],
    skillTags: ['writing', 'interviewing'],
    marketRelevance: 70,
    name: { en: 'Journalist', ru: 'Журналист', kk: 'Журналист' },
  },
  {
    slug: 'content_creator',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design', 'languages'],
    goalTags: ['express', 'independence'],
    skillTags: ['storytelling', 'editing'],
    marketRelevance: 84,
    name: { en: 'Content Creator', ru: 'Контент-креатор', kk: 'Контент жасаушы' },
  },
  {
    slug: 'marketing_specialist',
    route: 'creative',
    clusterBias: ['creator', 'strategist'],
    subjectTags: ['languages', 'business_economics'],
    goalTags: ['high_income', 'express'],
    skillTags: ['communication', 'analysis'],
    marketRelevance: 86,
    name: { en: 'Marketing Specialist', ru: 'Маркетолог', kk: 'Маркетолог' },
  },

  // --- Day-3 expansion to 8 careers per route ---
  // technological
  {
    slug: 'cloud_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator'],
    subjectTags: ['informatics'],
    goalTags: ['high_income', 'build_products'],
    skillTags: ['cloud', 'networks'],
    marketRelevance: 90,
    name: { en: 'Cloud Engineer', ru: 'Облачный инженер', kk: 'Бұлттық инженер' },
  },
  {
    slug: 'game_developer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'creator'],
    subjectTags: ['informatics', 'art_design'],
    goalTags: ['build_products', 'express'],
    skillTags: ['coding', 'design'],
    marketRelevance: 82,
    name: { en: 'Game Developer', ru: 'Разработчик игр', kk: 'Ойын жасаушы' },
  },
  {
    slug: 'devops_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'strategist'],
    subjectTags: ['informatics'],
    goalTags: ['high_income', 'build_things'],
    skillTags: ['automation', 'coding'],
    marketRelevance: 88,
    name: { en: 'DevOps Engineer', ru: 'DevOps-инженер', kk: 'DevOps инженері' },
  },
  // research
  {
    slug: 'chemist',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['chemistry'],
    goalTags: ['discover', 'understand_world'],
    skillTags: ['lab', 'analysis'],
    marketRelevance: 72,
    name: { en: 'Chemist', ru: 'Химик', kk: 'Химик' },
  },
  {
    slug: 'environmental_scientist',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['biology', 'geography'],
    goalTags: ['make_impact', 'help_people'],
    skillTags: ['research', 'fieldwork'],
    marketRelevance: 76,
    name: { en: 'Environmental Scientist', ru: 'Эколог', kk: 'Эколог' },
  },
  {
    slug: 'statistician',
    route: 'research',
    clusterBias: ['researcher', 'digital_innovator'],
    subjectTags: ['mathematics'],
    goalTags: ['solve_problems', 'high_income'],
    skillTags: ['statistics', 'analysis'],
    marketRelevance: 84,
    name: { en: 'Statistician', ru: 'Статистик', kk: 'Статистик' },
  },
  // managerial
  {
    slug: 'product_manager',
    route: 'managerial',
    clusterBias: ['strategist', 'digital_innovator'],
    subjectTags: ['business_economics', 'informatics'],
    goalTags: ['build_products', 'lead_teams'],
    skillTags: ['planning', 'communication'],
    marketRelevance: 89,
    name: { en: 'Product Manager', ru: 'Продакт-менеджер', kk: 'Өнім менеджері' },
  },
  {
    slug: 'financial_analyst',
    route: 'managerial',
    clusterBias: ['strategist', 'researcher'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['high_income', 'stability'],
    skillTags: ['analysis', 'finance'],
    marketRelevance: 86,
    name: { en: 'Financial Analyst', ru: 'Финансовый аналитик', kk: 'Қаржы талдаушысы' },
  },
  {
    slug: 'operations_manager',
    route: 'managerial',
    clusterBias: ['strategist'],
    subjectTags: ['business_economics', 'mathematics'],
    goalTags: ['lead_teams', 'stability'],
    skillTags: ['organization', 'planning'],
    marketRelevance: 80,
    name: { en: 'Operations Manager', ru: 'Операционный менеджер', kk: 'Операциялық менеджер' },
  },
  // social_humanitarian
  {
    slug: 'nurse',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['care', 'empathy'],
    marketRelevance: 84,
    name: { en: 'Nurse', ru: 'Медсестра', kk: 'Медбике' },
  },
  {
    slug: 'translator',
    route: 'social_humanitarian',
    clusterBias: ['creator', 'social_leader'],
    subjectTags: ['languages', 'literature'],
    goalTags: ['express', 'independence'],
    skillTags: ['languages', 'writing'],
    marketRelevance: 72,
    name: { en: 'Translator', ru: 'Переводчик', kk: 'Аудармашы' },
  },
  {
    slug: 'ngo_coordinator',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['social_science', 'languages'],
    goalTags: ['make_impact', 'help_people'],
    skillTags: ['organization', 'communication'],
    marketRelevance: 66,
    name: { en: 'NGO Coordinator', ru: 'Координатор НКО', kk: 'ҮЕҰ үйлестірушісі' },
  },
  // creative
  {
    slug: 'graphic_designer',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'build_products'],
    skillTags: ['design', 'visual'],
    marketRelevance: 80,
    name: { en: 'Graphic Designer', ru: 'Графический дизайнер', kk: 'Графикалық дизайнер' },
  },
  {
    slug: 'filmmaker',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['art_design', 'literature'],
    goalTags: ['tell_stories', 'express'],
    skillTags: ['storytelling', 'editing'],
    marketRelevance: 68,
    name: { en: 'Filmmaker', ru: 'Кинематографист', kk: 'Кинорежиссёр' },
  },
  {
    slug: 'music_producer',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'independence'],
    skillTags: ['production', 'audio'],
    marketRelevance: 66,
    name: { en: 'Music Producer', ru: 'Музыкальный продюсер', kk: 'Музыка продюсері' },
  },
]

export const CAREERS_BY_SLUG: Record<string, Career> = Object.fromEntries(
  CAREERS.map((c) => [c.slug, c]),
)
