import type { Locale } from '@/lib/i18n/config'
import type { Cluster } from './clusters'
import type { Route } from './routes'

// In-app mirror of supabase/seed.sql careers, used for the zero-backend demo
// (recommendations run client-side). CURATED DEMO DATA — `marketRelevance` is a
// curated demo signal, NOT live labor-market data. Subject tags use the same
// keys as onboarding favorite_subjects so overlap scoring works.

// --- Provenance (Day-6) ----------------------------------------------------
// Where a salary or demand signal comes from. Official sources are the Electronic
// Labour Exchange (Enbek, enbek.kz) and the Bureau of National Statistics
// (stat.gov.kz, average nominal wage by economic activity/region). `curated_estimate`
// means the figure is a hand-curated, clearly-labeled estimate that is NOT yet
// verified against those datasets. See docs/DATA_SOURCES.md.
export type SalarySource = 'enbek' | 'stat_gov_kz' | 'curated_estimate'
export type DemandSource = 'enbek' | 'curated_estimate'
export type DemandTrend = 'growing' | 'stable' | 'declining'

export interface Career {
  slug: string
  route: Route
  clusterBias: Cluster[]
  subjectTags: string[]
  goalTags: string[]
  skillTags: string[]
  marketRelevance: number // 0..100 curated demo relevance
  name: Record<Locale, string>
  // --- Optional provenance fields (all optional so existing data/consumers stay
  // valid). Displayed figures must be shown as curated estimates pending
  // verification against Enbek / stat.gov.kz. ---
  // TODO(provenance): replace curated estimates with verified Enbek/stat.gov.kz figures.
  salaryEstimateKzt?: string // e.g. "250000–450000 ₸/мес" — curated monthly range
  salarySource?: SalarySource
  demandTrend?: DemandTrend
  demandSource?: DemandSource
}

export const CAREERS: Career[] = [
  // technological
  {
    slug: 'software_developer',
    route: 'technological',
    clusterBias: ['digital_innovator'],
    subjectTags: ['informatics', 'mathematics'],
    goalTags: ['build_products', 'high_income'],
    skillTags: ['coding', 'problem_solving'],
    marketRelevance: 95,
    name: { en: 'Software Developer', ru: 'Разработчик ПО', kk: 'Бағдарламашы' },
    // Curated estimate anchored to stat.gov.kz "information & communication" sector
    // (~1.9x the national average nominal wage of ~423k ₸/mo, Q1 2025). Not verified.
    salaryEstimateKzt: '400000–900000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'data_analyst',
    route: 'technological',
    clusterBias: ['digital_innovator', 'researcher'],
    subjectTags: ['mathematics', 'informatics'],
    goalTags: ['high_income', 'solve_problems'],
    skillTags: ['analysis', 'statistics'],
    marketRelevance: 90,
    name: { en: 'Data Analyst', ru: 'Аналитик данных', kk: 'Дерек талдаушысы' },
    salaryEstimateKzt: '350000–750000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'ai_specialist',
    route: 'technological',
    clusterBias: ['digital_innovator', 'researcher'],
    subjectTags: ['mathematics', 'informatics'],
    goalTags: ['build_future', 'high_income'],
    skillTags: ['ml', 'coding'],
    marketRelevance: 96,
    name: { en: 'AI Specialist', ru: 'Специалист по ИИ', kk: 'ЖИ маманы' },
    salaryEstimateKzt: '500000–1200000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'cybersecurity_specialist',
    route: 'technological',
    clusterBias: ['digital_innovator', 'strategist'],
    subjectTags: ['informatics'],
    goalTags: ['protect_systems', 'high_income'],
    skillTags: ['security', 'networks'],
    marketRelevance: 92,
    name: {
      en: 'Cybersecurity Specialist',
      ru: 'Специалист по кибербезопасности',
      kk: 'Киберқауіпсіздік маманы',
    },
    salaryEstimateKzt: '450000–1000000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'robotics_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'creator'],
    subjectTags: ['physics', 'informatics'],
    goalTags: ['build_things'],
    skillTags: ['engineering', 'coding'],
    marketRelevance: 85,
    name: { en: 'Robotics Engineer', ru: 'Инженер-робототехник', kk: 'Робототехника инженері' },
  },
  // research
  {
    slug: 'psychologist',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['biology', 'social_science'],
    goalTags: ['help_people', 'understand_people'],
    skillTags: ['empathy', 'analysis'],
    marketRelevance: 80,
    name: { en: 'Psychologist', ru: 'Психолог', kk: 'Психолог' },
    salaryEstimateKzt: '200000–500000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'medical_doctor',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['diagnosis', 'care'],
    marketRelevance: 88,
    name: { en: 'Doctor', ru: 'Врач', kk: 'Дәрігер' },
    // Curated estimate; public-sector health wages sit near/below the national
    // average per stat.gov.kz, with wide private-clinic spread. Not verified.
    salaryEstimateKzt: '250000–600000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'biologist',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['discover', 'understand_world'],
    skillTags: ['research', 'lab'],
    marketRelevance: 75,
    name: { en: 'Biologist', ru: 'Биолог', kk: 'Биолог' },
  },
  {
    slug: 'economist_researcher',
    route: 'research',
    clusterBias: ['researcher', 'strategist'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['understand_world', 'high_income'],
    skillTags: ['analysis', 'modeling'],
    marketRelevance: 78,
    name: { en: 'Economist', ru: 'Экономист', kk: 'Экономист' },
    // Curated estimate anchored to stat.gov.kz "professional, scientific &
    // technical" sector (~1.5x national average). Not verified.
    salaryEstimateKzt: '300000–650000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'education_researcher',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['history', 'social_science'],
    goalTags: ['improve_education', 'help_people'],
    skillTags: ['research', 'writing'],
    marketRelevance: 70,
    name: {
      en: 'Education Researcher',
      ru: 'Исследователь в образовании',
      kk: 'Білім беру зерттеушісі',
    },
  },
  // managerial
  {
    slug: 'project_manager',
    route: 'managerial',
    clusterBias: ['strategist'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['lead_teams', 'high_income'],
    skillTags: ['planning', 'communication'],
    marketRelevance: 85,
    name: { en: 'Project Manager', ru: 'Менеджер проектов', kk: 'Жоба менеджері' },
    salaryEstimateKzt: '400000–800000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'entrepreneur',
    route: 'managerial',
    clusterBias: ['strategist', 'digital_innovator'],
    subjectTags: ['business_economics', 'mathematics'],
    goalTags: ['build_business', 'independence'],
    skillTags: ['leadership', 'risk'],
    marketRelevance: 88,
    name: { en: 'Entrepreneur', ru: 'Предприниматель', kk: 'Кәсіпкер' },
    // Highly variable; income depends on the venture. Curated, not verified.
    salaryEstimateKzt: '200000–2000000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'business_analyst',
    route: 'managerial',
    clusterBias: ['strategist', 'researcher'],
    subjectTags: ['mathematics', 'informatics', 'business_economics'],
    goalTags: ['solve_problems', 'high_income'],
    skillTags: ['analysis', 'communication'],
    marketRelevance: 84,
    name: { en: 'Business Analyst', ru: 'Бизнес-аналитик', kk: 'Бизнес-талдаушы' },
  },
  {
    slug: 'public_administration_specialist',
    route: 'managerial',
    clusterBias: ['strategist', 'social_leader'],
    subjectTags: ['history', 'social_science'],
    goalTags: ['serve_society', 'stability'],
    skillTags: ['policy', 'organization'],
    marketRelevance: 72,
    name: {
      en: 'Public Administration Specialist',
      ru: 'Специалист по госуправлению',
      kk: 'Мемлекеттік басқару маманы',
    },
  },
  {
    slug: 'lawyer',
    route: 'managerial',
    clusterBias: ['strategist', 'social_leader'],
    subjectTags: ['history', 'social_science'],
    goalTags: ['justice', 'high_income'],
    skillTags: ['argument', 'writing'],
    marketRelevance: 80,
    name: { en: 'Lawyer', ru: 'Юрист', kk: 'Заңгер' },
    salaryEstimateKzt: '300000–800000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  // social_humanitarian
  {
    slug: 'teacher',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['history', 'languages'],
    goalTags: ['help_people', 'shape_future'],
    skillTags: ['communication', 'patience'],
    marketRelevance: 82,
    name: { en: 'Teacher', ru: 'Учитель', kk: 'Мұғалім' },
    // Curated estimate; education-sector wages sit below the national average per
    // stat.gov.kz, though state pay reforms have raised them. Not verified.
    salaryEstimateKzt: '200000–450000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'hr_specialist',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['languages', 'social_science'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['empathy', 'organization'],
    marketRelevance: 76,
    name: { en: 'HR Specialist', ru: 'HR-специалист', kk: 'HR маманы' },
  },
  {
    slug: 'social_worker',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['social_science', 'history'],
    goalTags: ['help_people', 'make_impact'],
    skillTags: ['empathy', 'support'],
    marketRelevance: 70,
    name: { en: 'Social Worker', ru: 'Социальный работник', kk: 'Әлеуметтік қызметкер' },
    salaryEstimateKzt: '170000–350000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'diplomat',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['languages', 'history', 'geography'],
    goalTags: ['represent_country', 'travel'],
    skillTags: ['negotiation', 'languages'],
    marketRelevance: 74,
    name: { en: 'Diplomat', ru: 'Дипломат', kk: 'Дипломат' },
  },
  {
    slug: 'community_project_manager',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['social_science', 'history'],
    goalTags: ['make_impact', 'lead_teams'],
    skillTags: ['organization', 'communication'],
    marketRelevance: 68,
    name: {
      en: 'Community Project Manager',
      ru: 'Менеджер общественных проектов',
      kk: 'Қоғамдық жоба менеджері',
    },
  },
  // creative
  {
    slug: 'ux_ui_designer',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design', 'informatics'],
    goalTags: ['build_products', 'express'],
    skillTags: ['design', 'empathy'],
    marketRelevance: 88,
    name: { en: 'UX/UI Designer', ru: 'UX/UI-дизайнер', kk: 'UX/UI дизайнер' },
    // Curated estimate; digital/design roles trend toward the higher-paying
    // information & communication sector (stat.gov.kz). Not verified.
    salaryEstimateKzt: '300000–700000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'architect',
    route: 'creative',
    clusterBias: ['creator', 'strategist'],
    subjectTags: ['art_design', 'mathematics', 'physics'],
    goalTags: ['build_things', 'express'],
    skillTags: ['design', 'drafting'],
    marketRelevance: 80,
    name: { en: 'Architect', ru: 'Архитектор', kk: 'Сәулетші' },
    salaryEstimateKzt: '250000–600000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'journalist',
    route: 'creative',
    clusterBias: ['creator', 'social_leader'],
    subjectTags: ['languages', 'literature'],
    goalTags: ['tell_stories', 'make_impact'],
    skillTags: ['writing', 'interviewing'],
    marketRelevance: 70,
    name: { en: 'Journalist', ru: 'Журналист', kk: 'Журналист' },
  },
  {
    slug: 'content_creator',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design', 'languages'],
    goalTags: ['express', 'independence'],
    skillTags: ['storytelling', 'editing'],
    marketRelevance: 84,
    name: { en: 'Content Creator', ru: 'Контент-креатор', kk: 'Контент жасаушы' },
  },
  {
    slug: 'marketing_specialist',
    route: 'creative',
    clusterBias: ['creator', 'strategist'],
    subjectTags: ['languages', 'business_economics'],
    goalTags: ['high_income', 'express'],
    skillTags: ['communication', 'analysis'],
    marketRelevance: 86,
    name: { en: 'Marketing Specialist', ru: 'Маркетолог', kk: 'Маркетолог' },
    salaryEstimateKzt: '250000–600000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },

  // --- Day-3 expansion to 8 careers per route ---
  // technological
  {
    slug: 'cloud_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator'],
    subjectTags: ['informatics'],
    goalTags: ['high_income', 'build_products'],
    skillTags: ['cloud', 'networks'],
    marketRelevance: 90,
    name: { en: 'Cloud Engineer', ru: 'Облачный инженер', kk: 'Бұлттық инженер' },
    salaryEstimateKzt: '450000–950000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'game_developer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'creator'],
    subjectTags: ['informatics', 'art_design'],
    goalTags: ['build_products', 'express'],
    skillTags: ['coding', 'design'],
    marketRelevance: 82,
    name: { en: 'Game Developer', ru: 'Разработчик игр', kk: 'Ойын жасаушы' },
  },
  {
    slug: 'devops_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'strategist'],
    subjectTags: ['informatics'],
    goalTags: ['high_income', 'build_things'],
    skillTags: ['automation', 'coding'],
    marketRelevance: 88,
    name: { en: 'DevOps Engineer', ru: 'DevOps-инженер', kk: 'DevOps инженері' },
    salaryEstimateKzt: '500000–1000000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  // research
  {
    slug: 'chemist',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['chemistry'],
    goalTags: ['discover', 'understand_world'],
    skillTags: ['lab', 'analysis'],
    marketRelevance: 72,
    name: { en: 'Chemist', ru: 'Химик', kk: 'Химик' },
  },
  {
    slug: 'environmental_scientist',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['biology', 'geography'],
    goalTags: ['make_impact', 'help_people'],
    skillTags: ['research', 'fieldwork'],
    marketRelevance: 76,
    name: { en: 'Environmental Scientist', ru: 'Эколог', kk: 'Эколог' },
  },
  {
    slug: 'statistician',
    route: 'research',
    clusterBias: ['researcher', 'digital_innovator'],
    subjectTags: ['mathematics'],
    goalTags: ['solve_problems', 'high_income'],
    skillTags: ['statistics', 'analysis'],
    marketRelevance: 84,
    name: { en: 'Statistician', ru: 'Статистик', kk: 'Статистик' },
  },
  // managerial
  {
    slug: 'product_manager',
    route: 'managerial',
    clusterBias: ['strategist', 'digital_innovator'],
    subjectTags: ['business_economics', 'informatics'],
    goalTags: ['build_products', 'lead_teams'],
    skillTags: ['planning', 'communication'],
    marketRelevance: 89,
    name: { en: 'Product Manager', ru: 'Продакт-менеджер', kk: 'Өнім менеджері' },
  },
  {
    slug: 'financial_analyst',
    route: 'managerial',
    clusterBias: ['strategist', 'researcher'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['high_income', 'stability'],
    skillTags: ['analysis', 'finance'],
    marketRelevance: 86,
    name: { en: 'Financial Analyst', ru: 'Финансовый аналитик', kk: 'Қаржы талдаушысы' },
    // Curated estimate; finance/insurance is among the higher-paying sectors
    // (stat.gov.kz). Not verified.
    salaryEstimateKzt: '350000–800000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'operations_manager',
    route: 'managerial',
    clusterBias: ['strategist'],
    subjectTags: ['business_economics', 'mathematics'],
    goalTags: ['lead_teams', 'stability'],
    skillTags: ['organization', 'planning'],
    marketRelevance: 80,
    name: { en: 'Operations Manager', ru: 'Операционный менеджер', kk: 'Операциялық менеджер' },
  },
  // social_humanitarian
  {
    slug: 'nurse',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['care', 'empathy'],
    marketRelevance: 84,
    name: { en: 'Nurse', ru: 'Медсестра', kk: 'Медбике' },
    salaryEstimateKzt: '180000–400000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'growing',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'translator',
    route: 'social_humanitarian',
    clusterBias: ['creator', 'social_leader'],
    subjectTags: ['languages', 'literature'],
    goalTags: ['express', 'independence'],
    skillTags: ['languages', 'writing'],
    marketRelevance: 72,
    name: { en: 'Translator', ru: 'Переводчик', kk: 'Аудармашы' },
  },
  {
    slug: 'ngo_coordinator',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['social_science', 'languages'],
    goalTags: ['make_impact', 'help_people'],
    skillTags: ['organization', 'communication'],
    marketRelevance: 66,
    name: { en: 'NGO Coordinator', ru: 'Координатор НКО', kk: 'ҮЕҰ үйлестірушісі' },
  },
  // creative
  {
    slug: 'graphic_designer',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'build_products'],
    skillTags: ['design', 'visual'],
    marketRelevance: 80,
    name: { en: 'Graphic Designer', ru: 'Графический дизайнер', kk: 'Графикалық дизайнер' },
    salaryEstimateKzt: '200000–500000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'filmmaker',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['art_design', 'literature'],
    goalTags: ['tell_stories', 'express'],
    skillTags: ['storytelling', 'editing'],
    marketRelevance: 68,
    name: { en: 'Filmmaker', ru: 'Кинематографист', kk: 'Кинорежиссёр' },
  },
  {
    slug: 'music_producer',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'independence'],
    skillTags: ['production', 'audio'],
    marketRelevance: 66,
    name: { en: 'Music Producer', ru: 'Музыкальный продюсер', kk: 'Музыка продюсері' },
  },

  // --- Day-6 expansion to production catalog (>=100 careers, ~20 per route) ---
  // TODO(provenance): marketRelevance is a curated demo signal, not live
  // labor-market data; replace with sourced KZ demand/salary data when available.

  // technological
  {
    slug: 'mobile_app_developer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'creator'],
    subjectTags: ['informatics', 'mathematics'],
    goalTags: ['build_products', 'high_income'],
    skillTags: ['coding', 'design'],
    marketRelevance: 89,
    name: { en: 'Mobile App Developer', ru: 'Разработчик мобильных приложений', kk: 'Мобильді қосымша жасаушы' },
  },
  {
    slug: 'web_developer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'creator'],
    subjectTags: ['informatics'],
    goalTags: ['build_products', 'independence'],
    skillTags: ['coding', 'design'],
    marketRelevance: 87,
    name: { en: 'Web Developer', ru: 'Веб-разработчик', kk: 'Веб-әзірлеуші' },
  },
  {
    slug: 'database_administrator',
    route: 'technological',
    clusterBias: ['digital_innovator', 'strategist'],
    subjectTags: ['informatics', 'mathematics'],
    goalTags: ['stability', 'solve_problems'],
    skillTags: ['organization', 'analysis'],
    marketRelevance: 80,
    name: { en: 'Database Administrator', ru: 'Администратор баз данных', kk: 'Дерекқор әкімшісі' },
  },
  {
    slug: 'network_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator'],
    subjectTags: ['informatics', 'physics'],
    goalTags: ['stability', 'build_things'],
    skillTags: ['networks', 'problem_solving'],
    marketRelevance: 81,
    name: { en: 'Network Engineer', ru: 'Сетевой инженер', kk: 'Желілік инженер' },
  },
  {
    slug: 'qa_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'researcher'],
    subjectTags: ['informatics'],
    goalTags: ['solve_problems', 'build_products'],
    skillTags: ['analysis', 'automation'],
    marketRelevance: 82,
    name: { en: 'QA Engineer', ru: 'Инженер по тестированию', kk: 'Тестілеу инженері' },
  },
  {
    slug: 'data_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'researcher'],
    subjectTags: ['informatics', 'mathematics'],
    goalTags: ['high_income', 'solve_problems'],
    skillTags: ['coding', 'analysis'],
    marketRelevance: 90,
    name: { en: 'Data Engineer', ru: 'Инженер данных', kk: 'Дерек инженері' },
  },
  {
    slug: 'embedded_systems_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'creator'],
    subjectTags: ['physics', 'informatics'],
    goalTags: ['build_things', 'solve_problems'],
    skillTags: ['engineering', 'coding'],
    marketRelevance: 78,
    name: { en: 'Embedded Systems Engineer', ru: 'Инженер встраиваемых систем', kk: 'Ендірілген жүйелер инженері' },
  },
  {
    slug: 'blockchain_developer',
    route: 'technological',
    clusterBias: ['digital_innovator'],
    subjectTags: ['informatics', 'mathematics'],
    goalTags: ['build_future', 'high_income'],
    skillTags: ['coding', 'security'],
    marketRelevance: 76,
    name: { en: 'Blockchain Developer', ru: 'Разработчик блокчейна', kk: 'Блокчейн әзірлеушісі' },
  },
  {
    slug: 'machine_learning_engineer',
    route: 'technological',
    clusterBias: ['digital_innovator', 'researcher'],
    subjectTags: ['mathematics', 'informatics'],
    goalTags: ['build_future', 'high_income'],
    skillTags: ['ml', 'coding'],
    marketRelevance: 94,
    name: { en: 'Machine Learning Engineer', ru: 'Инженер по машинному обучению', kk: 'Машиналық оқыту инженері' },
  },
  {
    slug: 'it_support_specialist',
    route: 'technological',
    clusterBias: ['digital_innovator', 'social_leader'],
    subjectTags: ['informatics'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['support', 'problem_solving'],
    marketRelevance: 74,
    name: { en: 'IT Support Specialist', ru: 'Специалист технической поддержки', kk: 'Техникалық қолдау маманы' },
  },
  {
    slug: 'systems_administrator',
    route: 'technological',
    clusterBias: ['digital_innovator', 'strategist'],
    subjectTags: ['informatics'],
    goalTags: ['stability', 'solve_problems'],
    skillTags: ['networks', 'organization'],
    marketRelevance: 77,
    name: { en: 'Systems Administrator', ru: 'Системный администратор', kk: 'Жүйелік әкімші' },
  },
  {
    slug: 'geospatial_analyst',
    route: 'technological',
    clusterBias: ['digital_innovator', 'researcher'],
    subjectTags: ['informatics', 'geography'],
    goalTags: ['solve_problems', 'make_impact'],
    skillTags: ['analysis', 'modeling'],
    marketRelevance: 75,
    name: { en: 'Geospatial Analyst', ru: 'Геопространственный аналитик', kk: 'Геокеңістік талдаушысы' },
  },

  // research
  {
    slug: 'physicist',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['physics', 'mathematics'],
    goalTags: ['discover', 'understand_world'],
    skillTags: ['research', 'modeling'],
    marketRelevance: 72,
    name: { en: 'Physicist', ru: 'Физик', kk: 'Физик' },
  },
  {
    slug: 'mathematician',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['mathematics'],
    goalTags: ['discover', 'solve_problems'],
    skillTags: ['analysis', 'modeling'],
    marketRelevance: 73,
    name: { en: 'Mathematician', ru: 'Математик', kk: 'Математик' },
  },
  {
    slug: 'geologist',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['geography', 'chemistry'],
    goalTags: ['discover', 'understand_world'],
    skillTags: ['fieldwork', 'analysis'],
    marketRelevance: 78,
    name: { en: 'Geologist', ru: 'Геолог', kk: 'Геолог' },
    // Curated estimate anchored to stat.gov.kz "mining & quarrying" sector, the
    // highest-paying activity (~2.1x national average). Not verified.
    salaryEstimateKzt: '400000–1000000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'pharmacist',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['chemistry', 'biology'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['care', 'analysis'],
    marketRelevance: 80,
    name: { en: 'Pharmacist', ru: 'Фармацевт', kk: 'Фармацевт' },
  },
  {
    slug: 'biotechnologist',
    route: 'research',
    clusterBias: ['researcher', 'digital_innovator'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['build_future', 'discover'],
    skillTags: ['lab', 'research'],
    marketRelevance: 82,
    name: { en: 'Biotechnologist', ru: 'Биотехнолог', kk: 'Биотехнолог' },
  },
  {
    slug: 'agronomist',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['biology', 'geography'],
    goalTags: ['make_impact', 'understand_world'],
    skillTags: ['fieldwork', 'analysis'],
    marketRelevance: 76,
    name: { en: 'Agronomist', ru: 'Агроном', kk: 'Агроном' },
  },
  {
    slug: 'veterinarian',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['diagnosis', 'care'],
    marketRelevance: 77,
    name: { en: 'Veterinarian', ru: 'Ветеринар', kk: 'Ветеринар' },
  },
  {
    slug: 'astronomer',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['physics', 'mathematics'],
    goalTags: ['discover', 'understand_world'],
    skillTags: ['research', 'analysis'],
    marketRelevance: 68,
    name: { en: 'Astronomer', ru: 'Астроном', kk: 'Астроном' },
  },
  {
    slug: 'epidemiologist',
    route: 'research',
    clusterBias: ['researcher', 'social_leader'],
    subjectTags: ['biology', 'mathematics'],
    goalTags: ['help_people', 'understand_world'],
    skillTags: ['statistics', 'research'],
    marketRelevance: 81,
    name: { en: 'Epidemiologist', ru: 'Эпидемиолог', kk: 'Эпидемиолог' },
  },
  {
    slug: 'linguistics_researcher',
    route: 'research',
    clusterBias: ['researcher', 'creator'],
    subjectTags: ['languages', 'literature'],
    goalTags: ['discover', 'understand_world'],
    skillTags: ['research', 'writing'],
    marketRelevance: 66,
    name: { en: 'Linguistics Researcher', ru: 'Исследователь-лингвист', kk: 'Лингвист-зерттеуші' },
  },
  {
    slug: 'historian',
    route: 'research',
    clusterBias: ['researcher'],
    subjectTags: ['history', 'social_science'],
    goalTags: ['understand_world', 'discover'],
    skillTags: ['research', 'writing'],
    marketRelevance: 64,
    name: { en: 'Historian', ru: 'Историк', kk: 'Тарихшы' },
  },
  {
    slug: 'materials_scientist',
    route: 'research',
    clusterBias: ['researcher', 'digital_innovator'],
    subjectTags: ['chemistry', 'physics'],
    goalTags: ['discover', 'build_future'],
    skillTags: ['lab', 'research'],
    marketRelevance: 79,
    name: { en: 'Materials Scientist', ru: 'Материаловед', kk: 'Материалтанушы' },
  },

  // managerial
  {
    slug: 'marketing_manager',
    route: 'managerial',
    clusterBias: ['strategist', 'creator'],
    subjectTags: ['business_economics', 'languages'],
    goalTags: ['lead_teams', 'high_income'],
    skillTags: ['planning', 'communication'],
    marketRelevance: 83,
    name: { en: 'Marketing Manager', ru: 'Менеджер по маркетингу', kk: 'Маркетинг менеджері' },
  },
  {
    slug: 'sales_manager',
    route: 'managerial',
    clusterBias: ['strategist', 'social_leader'],
    subjectTags: ['business_economics'],
    goalTags: ['high_income', 'lead_teams'],
    skillTags: ['communication', 'negotiation'],
    marketRelevance: 80,
    name: { en: 'Sales Manager', ru: 'Менеджер по продажам', kk: 'Сату менеджері' },
  },
  {
    slug: 'accountant',
    route: 'managerial',
    clusterBias: ['strategist'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['stability', 'solve_problems'],
    skillTags: ['finance', 'organization'],
    marketRelevance: 78,
    name: { en: 'Accountant', ru: 'Бухгалтер', kk: 'Бухгалтер' },
    salaryEstimateKzt: '220000–500000 ₸/мес',
    salarySource: 'curated_estimate',
    demandTrend: 'stable',
    demandSource: 'curated_estimate',
  },
  {
    slug: 'auditor',
    route: 'managerial',
    clusterBias: ['strategist', 'researcher'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['stability', 'high_income'],
    skillTags: ['analysis', 'finance'],
    marketRelevance: 77,
    name: { en: 'Auditor', ru: 'Аудитор', kk: 'Аудитор' },
  },
  {
    slug: 'supply_chain_manager',
    route: 'managerial',
    clusterBias: ['strategist'],
    subjectTags: ['business_economics', 'mathematics'],
    goalTags: ['lead_teams', 'solve_problems'],
    skillTags: ['organization', 'planning'],
    marketRelevance: 79,
    name: { en: 'Supply Chain Manager', ru: 'Менеджер цепочек поставок', kk: 'Жабдықтау тізбегінің менеджері' },
  },
  {
    slug: 'investment_banker',
    route: 'managerial',
    clusterBias: ['strategist', 'researcher'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['high_income', 'solve_problems'],
    skillTags: ['finance', 'analysis'],
    marketRelevance: 82,
    name: { en: 'Investment Banker', ru: 'Инвестиционный банкир', kk: 'Инвестициялық банкир' },
  },
  {
    slug: 'management_consultant',
    route: 'managerial',
    clusterBias: ['strategist', 'researcher'],
    subjectTags: ['business_economics', 'mathematics'],
    goalTags: ['solve_problems', 'high_income'],
    skillTags: ['analysis', 'communication'],
    marketRelevance: 84,
    name: { en: 'Management Consultant', ru: 'Управленческий консультант', kk: 'Басқару кеңесшісі' },
  },
  {
    slug: 'logistics_specialist',
    route: 'managerial',
    clusterBias: ['strategist'],
    subjectTags: ['business_economics', 'geography'],
    goalTags: ['stability', 'solve_problems'],
    skillTags: ['organization', 'planning'],
    marketRelevance: 76,
    name: { en: 'Logistics Specialist', ru: 'Специалист по логистике', kk: 'Логистика маманы' },
  },
  {
    slug: 'real_estate_developer',
    route: 'managerial',
    clusterBias: ['strategist', 'creator'],
    subjectTags: ['business_economics', 'geography'],
    goalTags: ['build_business', 'high_income'],
    skillTags: ['planning', 'negotiation'],
    marketRelevance: 72,
    name: { en: 'Real Estate Developer', ru: 'Девелопер недвижимости', kk: 'Жылжымайтын мүлік девелоперы' },
  },
  {
    slug: 'risk_manager',
    route: 'managerial',
    clusterBias: ['strategist', 'researcher'],
    subjectTags: ['mathematics', 'business_economics'],
    goalTags: ['stability', 'solve_problems'],
    skillTags: ['analysis', 'finance'],
    marketRelevance: 78,
    name: { en: 'Risk Manager', ru: 'Риск-менеджер', kk: 'Тәуекел менеджері' },
  },
  {
    slug: 'public_policy_analyst',
    route: 'managerial',
    clusterBias: ['strategist', 'social_leader'],
    subjectTags: ['social_science', 'business_economics'],
    goalTags: ['serve_society', 'make_impact'],
    skillTags: ['policy', 'analysis'],
    marketRelevance: 70,
    name: { en: 'Public Policy Analyst', ru: 'Аналитик государственной политики', kk: 'Мемлекеттік саясат талдаушысы' },
  },
  {
    slug: 'civil_servant',
    route: 'managerial',
    clusterBias: ['strategist', 'social_leader'],
    subjectTags: ['social_science', 'history'],
    goalTags: ['serve_society', 'stability'],
    skillTags: ['organization', 'policy'],
    marketRelevance: 71,
    name: { en: 'Civil Servant', ru: 'Государственный служащий', kk: 'Мемлекеттік қызметкер' },
  },

  // social_humanitarian
  {
    slug: 'school_counselor',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['social_science', 'languages'],
    goalTags: ['help_people', 'shape_future'],
    skillTags: ['empathy', 'communication'],
    marketRelevance: 74,
    name: { en: 'School Counselor', ru: 'Школьный психолог-консультант', kk: 'Мектеп кеңесшісі' },
  },
  {
    slug: 'physiotherapist',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'researcher'],
    subjectTags: ['biology'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['care', 'support'],
    marketRelevance: 76,
    name: { en: 'Physiotherapist', ru: 'Физиотерапевт', kk: 'Физиотерапевт' },
  },
  {
    slug: 'kindergarten_teacher',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'creator'],
    subjectTags: ['languages', 'art_design'],
    goalTags: ['help_people', 'shape_future'],
    skillTags: ['patience', 'communication'],
    marketRelevance: 72,
    name: { en: 'Kindergarten Teacher', ru: 'Воспитатель детского сада', kk: 'Балабақша тәрбиешісі' },
  },
  {
    slug: 'special_education_teacher',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['social_science', 'languages'],
    goalTags: ['help_people', 'make_impact'],
    skillTags: ['patience', 'empathy'],
    marketRelevance: 73,
    name: { en: 'Special Education Teacher', ru: 'Педагог специального образования', kk: 'Арнайы білім беру педагогы' },
  },
  {
    slug: 'speech_therapist',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'researcher'],
    subjectTags: ['biology', 'languages'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['care', 'patience'],
    marketRelevance: 71,
    name: { en: 'Speech Therapist', ru: 'Логопед', kk: 'Логопед' },
  },
  {
    slug: 'librarian',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'researcher'],
    subjectTags: ['literature', 'history'],
    goalTags: ['help_people', 'shape_future'],
    skillTags: ['organization', 'research'],
    marketRelevance: 62,
    name: { en: 'Librarian', ru: 'Библиотекарь', kk: 'Кітапханашы' },
  },
  {
    slug: 'paramedic',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['biology', 'chemistry'],
    goalTags: ['help_people', 'stability'],
    skillTags: ['care', 'diagnosis'],
    marketRelevance: 75,
    name: { en: 'Paramedic', ru: 'Фельдшер скорой помощи', kk: 'Жедел жәрдем фельдшері' },
  },
  {
    slug: 'youth_worker',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['social_science'],
    goalTags: ['help_people', 'make_impact'],
    skillTags: ['empathy', 'support'],
    marketRelevance: 64,
    name: { en: 'Youth Worker', ru: 'Специалист по работе с молодёжью', kk: 'Жастармен жұмыс маманы' },
  },
  {
    slug: 'career_counselor',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'strategist'],
    subjectTags: ['social_science', 'languages'],
    goalTags: ['help_people', 'shape_future'],
    skillTags: ['communication', 'empathy'],
    marketRelevance: 70,
    name: { en: 'Career Counselor', ru: 'Карьерный консультант', kk: 'Мансап кеңесшісі' },
  },
  {
    slug: 'public_health_specialist',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'researcher'],
    subjectTags: ['biology', 'social_science'],
    goalTags: ['help_people', 'make_impact'],
    skillTags: ['organization', 'analysis'],
    marketRelevance: 77,
    name: { en: 'Public Health Specialist', ru: 'Специалист общественного здравоохранения', kk: 'Қоғамдық денсаулық сақтау маманы' },
  },
  {
    slug: 'language_teacher',
    route: 'social_humanitarian',
    clusterBias: ['social_leader', 'creator'],
    subjectTags: ['languages', 'literature'],
    goalTags: ['help_people', 'shape_future'],
    skillTags: ['communication', 'languages'],
    marketRelevance: 76,
    name: { en: 'Language Teacher', ru: 'Преподаватель языков', kk: 'Тіл оқытушысы' },
  },
  {
    slug: 'sports_coach',
    route: 'social_humanitarian',
    clusterBias: ['social_leader'],
    subjectTags: ['biology', 'social_science'],
    goalTags: ['help_people', 'shape_future'],
    skillTags: ['leadership', 'patience'],
    marketRelevance: 68,
    name: { en: 'Sports Coach', ru: 'Спортивный тренер', kk: 'Спорт жаттықтырушысы' },
  },

  // creative
  {
    slug: 'interior_designer',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'build_things'],
    skillTags: ['design', 'visual'],
    marketRelevance: 74,
    name: { en: 'Interior Designer', ru: 'Дизайнер интерьеров', kk: 'Интерьер дизайнері' },
  },
  {
    slug: 'fashion_designer',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'build_products'],
    skillTags: ['design', 'visual'],
    marketRelevance: 70,
    name: { en: 'Fashion Designer', ru: 'Дизайнер одежды', kk: 'Сән дизайнері' },
  },
  {
    slug: 'animator',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design', 'informatics'],
    goalTags: ['express', 'tell_stories'],
    skillTags: ['design', 'storytelling' ],
    marketRelevance: 76,
    name: { en: 'Animator', ru: 'Аниматор', kk: 'Аниматор' },
  },
  {
    slug: 'photographer',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'independence'],
    skillTags: ['visual', 'editing'],
    marketRelevance: 66,
    name: { en: 'Photographer', ru: 'Фотограф', kk: 'Фотограф' },
  },
  {
    slug: 'copywriter',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['languages', 'literature'],
    goalTags: ['express', 'tell_stories'],
    skillTags: ['writing', 'storytelling'],
    marketRelevance: 72,
    name: { en: 'Copywriter', ru: 'Копирайтер', kk: 'Копирайтер' },
  },
  {
    slug: 'art_director',
    route: 'creative',
    clusterBias: ['creator', 'strategist'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'lead_teams'],
    skillTags: ['design', 'leadership'],
    marketRelevance: 78,
    name: { en: 'Art Director', ru: 'Арт-директор', kk: 'Арт-директор' },
  },
  {
    slug: 'industrial_designer',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design', 'physics'],
    goalTags: ['build_things', 'express'],
    skillTags: ['design', 'drafting'],
    marketRelevance: 73,
    name: { en: 'Industrial Designer', ru: 'Промышленный дизайнер', kk: 'Өнеркәсіптік дизайнер' },
  },
  {
    slug: 'motion_designer',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design', 'informatics'],
    goalTags: ['express', 'build_products'],
    skillTags: ['design', 'editing'],
    marketRelevance: 75,
    name: { en: 'Motion Designer', ru: 'Моушн-дизайнер', kk: 'Моушн-дизайнер' },
  },
  {
    slug: 'illustrator',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['art_design'],
    goalTags: ['express', 'tell_stories'],
    skillTags: ['design', 'visual'],
    marketRelevance: 64,
    name: { en: 'Illustrator', ru: 'Иллюстратор', kk: 'Суретші-иллюстратор' },
  },
  {
    slug: 'pr_specialist',
    route: 'creative',
    clusterBias: ['creator', 'social_leader'],
    subjectTags: ['languages', 'social_science'],
    goalTags: ['make_impact', 'express'],
    skillTags: ['communication', 'writing'],
    marketRelevance: 74,
    name: { en: 'PR Specialist', ru: 'Специалист по связям с общественностью', kk: 'Қоғаммен байланыс маманы' },
  },
  {
    slug: 'editor',
    route: 'creative',
    clusterBias: ['creator'],
    subjectTags: ['languages', 'literature'],
    goalTags: ['tell_stories', 'express'],
    skillTags: ['editing', 'writing'],
    marketRelevance: 68,
    name: { en: 'Editor', ru: 'Редактор', kk: 'Редактор' },
  },
  {
    slug: 'sound_engineer',
    route: 'creative',
    clusterBias: ['creator', 'digital_innovator'],
    subjectTags: ['art_design', 'physics'],
    goalTags: ['express', 'build_things'],
    skillTags: ['audio', 'production'],
    marketRelevance: 66,
    name: { en: 'Sound Engineer', ru: 'Звукорежиссёр', kk: 'Дыбыс режиссёрі' },
  },
]

export const CAREERS_BY_SLUG: Record<string, Career> = Object.fromEntries(
  CAREERS.map((c) => [c.slug, c]),
)
